const Products = [
  {
    categoryName: 'Coffee',
    categoryId: 0,
    sku: '01',
    image: '',
    name: 'Freddo Espresso',
    description:
      '- Ipanema Freddo Espresso',
    price: 2.50,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 0,
  },

  {
    categoryName: 'Coffee',
    categoryId: 0,
    sku: '02',
    image: '',
    name: 'Freddo Cappuccino',
    description: '- Ipanema Freddo Cappuccino',
    price: 3.00,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 0,
  },
  {
    categoryName: 'Coffee',
    categoryId: 0,
    sku: '03',
    image: '/image/bunrieu.jpg',
    name: 'Espresso',
    description: '- Ipanema Espresso',
    price: 2.00,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 0,
  },
  {
    categoryName: 'Coffee',
    categoryId: 0,
    sku: '04',
    image: '',
    name: 'Double Espresso',
    description: '- Ipanema Double Espresso',
    price: 2.50,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 0,
  },
  {
    categoryName: 'Coffee',
    categoryId: 0,
    sku: '06',
    image: '',
    name: 'Double Cappuccino',
    description:
      '- Ipanema Double Cappuccino',
    price: 2.50,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 0,
  },
  {
    categoryName: 'Beers',
    categoryId: 1,
    sku: '07',
    image: '',
    name: 'Heineken',
    description: '- Heineken Beer 500ml',
    price: 3.50,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 1,
  },
  {
    categoryName: 'Amstel',
    categoryId: 1,
    sku: '08',
    image: '',
    name: 'Amstel',
    description: '- Amstel Beer 500ml',
    price: 3.50,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 1,
  },
  {
    categoryName: 'Beers',
    categoryId: 1,
    sku: '09',
    image: '',
    name: 'Kaizer',
    description:
      '- Kaizer Beer 500ml',
    price: 4.00,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 1,
  },
  {
    categoryName: 'Beers',
    categoryId: 1,
    sku: '10',
    image: '',
    name: 'Fisher',
    description: '- Fisher Beer 500ml',
    price: 4.00,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 1,
  },
  {
    categoryName: 'Food',
    categoryId: 2,
    sku: '11',
    image: '',
    name: 'Pizza',
    description: '- Freshly baked dough topped with rich tomato sauce, melted mozzarella, and a variety of carefully selected toppings, finished to golden perfection',
    price: 8.00,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 3,
  },
  {
    categoryName: 'Food',
    categoryId: 2,
    sku: '12',
    image: '',
    name: 'Ntakos',
    description: '- Traditional Cretan barley rusks topped with ripe tomatoes, creamy feta, extra virgin olive oil, and aromatic herbs for a fresh, authentic taste. ',
    price: 8.00,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 3,
  },
  {
    categoryName: 'Food',
    categoryId: 2,
    sku: '13',
    image: '',
    name: 'Chicken Nuggets',
    description:
      '- 1 portion of chicken nuggets, served with dipping sauce',
    price: 8.00,
    costPrice: 0,
    count: 0,
    inStock: 0  ,
    sortOrder: 5,
  },
  {
    categoryName: 'Food',
    categoryId: 2,
    sku: '14',
    image: '',
    name: 'Cretan platter with apaki',
    description:
      '- A selection of traditional Cretan delicacies featuring smoked pork apaki, accompanied by local cheeses, barley rusks, and authentic flavors of Crete.',
    price: 8.00,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 5,
  },
  {
    categoryName: 'Food',
    categoryId: 2,
    sku: '15',
    image: '',
    name: 'Sausage platter',
    description:
      'A generous selection of grilled sausages, served with mustard, fresh bread, and flavorful accompaniments—perfect for sharing.',
    price: 8.00,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 5,
  },
  {
    categoryName: 'Drinks',
    categoryId: 3,
    sku: '16',
    image: '',
    name: 'Coca-Cola',
    description:
      'Classic, ice-cold Coca-Cola with its refreshing sparkle and unmistakable taste.',
    price: 2.50,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 5,
  },
  {
    categoryName: 'Drinks',
    categoryId: 3,
    sku: '17',
    image: '',
    name: 'Sprite',
    description:
      'A crisp and refreshing lemon-lime soft drink, served chilled for a light and invigorating taste.',
    price: 2.50,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 5,
  },
  {
    categoryName: 'Drinks',
    categoryId: 3,
    sku: '18',
    image: '',
    name: 'Orange Juice',
    description:
      'Fresh and refreshing orange juice, full of natural citrus flavor and served chilled.',
    price: 2.50,
    costPrice: 0,
    count: 0,
    inStock: 0,
    sortOrder: 5,
  },
  
];

export default Products;
